CREATE TABLE tb_training_program_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainee_id BIGINT NOT NULL,
    training_program_id BIGINT NOT NULL,
    CONSTRAINT uk_training_application_trainee_program UNIQUE (trainee_id, training_program_id)
);

CREATE INDEX ix_training_application_program ON tb_training_program_application (training_program_id);

CREATE TABLE tb_standard_program_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT NOT NULL,
    standard_program_id BIGINT NOT NULL,
    CONSTRAINT uk_standard_application_participant_program UNIQUE (participant_id, standard_program_id)
);

CREATE INDEX ix_standard_application_program ON tb_standard_program_application (standard_program_id);
